# Generated by Django 4.1.7 on 2023-03-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='con_password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
