# Generated by Django 4.1.7 on 2023-03-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_app', '0007_staff_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_reg',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
