# Generated by Django 4.1.7 on 2023-03-28 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_app', '0009_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('pickup_place', models.CharField(max_length=100, null=True)),
                ('to_place', models.CharField(max_length=100, null=True)),
                ('mobile', models.CharField(max_length=100, null=True)),
                ('time', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(max_length=100, null=True)),
                ('car_type', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hiring_app.driver_reg')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hiring_app.user_reg')),
            ],
        ),
    ]
