# Generated by Django 4.1.7 on 2023-04-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_app', '0011_driver_reg_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veh_type', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
