# Generated by Django 4.1.7 on 2023-04-04 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_app', '0012_vehicle_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vehicle_type',
        ),
    ]
