# Generated by Django 4.1.7 on 2023-04-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_app', '0014_driver_reg_veh_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='km_per_amt',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trips',
            name='kms',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trips',
            name='total_amt',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
