# Generated by Django 4.1.7 on 2023-04-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_app', '0015_trips_km_per_amt_trips_kms_trips_total_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='payment',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
